name: Terraform Pipeline


on:
  push:
    branches:
     - main
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Checkov
        run: |
          python3 -m pip install --upgrade pip
          pip install checkov

      - name: Run Checkov scan
        run:  checkov -f ./Lab_1/main.tf --skip-check CKV_AWS_130,CKV_AWS_260,CKV_AWS_24,CKV_AWS_277,CKV_AWS_25,CKV_AWS_23,CKV_AWS_79,CKV_AWS_135,CKV_AWS_126,CKV_AWS_8,CKV2_AWS_12,CKV2_AWS_5,CKV2_AWS_11,CKV2_AWS_41,CKV2_AWS_19


  deploy:
    # This job depends on the `check` job and will only run if `check` succeeds
    needs: check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.7 

      - name: Check Terraform and AWS Connection
        run: |
          terraform version
          aws sts get-caller-identity

      - name: Apply Terraform
        run: |
          terraform init
          terraform plan
          terraform apply --auto-approve
        working-directory: ./Lab_1
